name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev
          sudo apt-get install -y debhelper dh-make

      - name: Configure and Build
        run: |
          mkdir -p build && cd build
          cmake .. -DBUILD_TESTING=ON
          make
          ctest --output-on-failure

      - name: Build .deb package
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ../*.deb

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: ../*.deb
