name: Build and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          debhelper \
          dh-make

    - name: Configure project
      run: |
        mkdir -p build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build project
      run: |
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel $(nproc)

    - name: Run tests
      working-directory: ./build
      run: |
        ctest --output-on-failure --parallel $(nproc)

    - name: Create DEB package
      run: |
        mkdir -p package/usr/local/bin
        install -D -m 755 build/main package/usr/local/bin/builder-pattern
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: builder-pattern
        Version: 1.0.0
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Builder Pattern Implementation
        EOF
        
        dpkg-deb --build package builder-pattern.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: builder-pattern-package
        path: |
          builder-pattern.deb
          build/compile_commands.json  # если нужен
