name: Build and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Было v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          debhelper \
          dh-make

    - name: Clean workspace
      run: |
        rm -rf build
        mkdir -p build

    - name: Configure project
      working-directory: ./build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      working-directory: ./build
      run: cmake --build . --config Release --parallel $(nproc)

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure --parallel $(nproc)

    - name: Prepare DEB package
      run: |
        mkdir -p package/usr/local/bin
        install -D -m 755 build/main package/usr/local/bin/builder-pattern
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: builder-pattern
        Version: 1.0.0
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Builder Design Pattern implementation
        EOF

    - name: Build DEB package
      run: dpkg-deb --build package builder-pattern.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Было v2
      with:
        name: builder-pattern
        path: builder-pattern.deb
