name: Build and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-22.04  # Явно указываем версию Ubuntu
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Только актуальная версия

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          debhelper \
          dh-make

    - name: Clean build directory
      run: rm -rf build

    - name: Configure project
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        cmake --build . --parallel $(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p package/usr/local/bin
        install -D -m 755 build/main package/usr/local/bin/builder-pattern
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: builder-pattern
        Version: 1.0.0
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Builder Pattern Example
        EOF
        
        dpkg-deb --build package builder-pattern.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Только актуальная версия
      with:
        name: builder-pattern
        path: builder-pattern.deb
