name: Build and Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # Необходимо для создания релизов

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Обновлено с v2 до v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          debhelper \
          dh-make \
          git

    - name: Clean workspace
      run: |
        rm -rf build
        rm -rf package
        rm -f *.deb

    - name: Configure project
      run: |
        mkdir -p build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cmake --build build --config Release --parallel $(nproc)

    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure --parallel $(nproc)

    - name: Get version from tag
      id: get-version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="0.0.0-dev"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Using version: ${VERSION}"

    - name: Prepare DEB package
      run: |
        mkdir -p package/usr/local/bin
        install -D -m 755 build/main package/usr/local/bin/builder-pattern
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: builder-pattern
        Version: ${{ steps.get-version.outputs.version }}
        Section: devel
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: Builder Design Pattern implementation
        EOF

    - name: Build DEB package
      run: |
        dpkg-deb --build package builder-pattern_${{ steps.get-version.outputs.version }}_amd64.deb
        ls -lh *.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Обновлено с v2 до v4
      with:
        name: builder-pattern-deb
        path: builder-pattern_${{ steps.get-version.outputs.version }}_amd64.deb

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: builder-pattern_${{ steps.get-version.outputs.version }}_amd64.deb
        generate_release_notes: true
